### ISSUE TITLE
What are the "w" and self.mask in line 18 and line 75 in the model.py? 

### ISSUE THREAD

**Issue by CXX1113** [amirkhas/GraphMemoryNet#2]
Thank you.

**Comment by amirkhas** [comment]
Hi, thanks for your interest.
-- As you can see in line 22 of model.py, "w" is used for initializing the centroids.
-- Not all the graphs in the same dataset have the same size, so one way of padding, for efficiency, is by zero-padding the adjacencies in a tensor. self.mask in line 75 is a mask to keep track of the graph sizes and ignore the zero-padded ones in assignment matrix calculations.
I hope my answers are clear.

**Comment by CXX1113** [comment]
I see, thank you for your answer.
