### ISSUE TITLE
Predict The Sequence of Dialog in Comic Books

### ISSUE THREAD

**Issue by ghost** [amirkhas/GraphMemoryNet#4]
Thanks for your hard work!

Take this example, i want to predict the order of the dialog boxes in a comic book, basically telling which dialog box is 1st, which is 2nd, 3rd, etc...
- note that i have a big dataset as a ground-truth to represent the order that humans read to train a new graph model.

- For the new images that i want to predict, i already have the dialog boxes location and coordinated detected using Detectron , 
 now i want to predict their reading-order.

- Can your code be trained to solve such task. Perhaps i represent the detected dialog boxes as nodes?
- **Can it generalize on unseen data**. Will it really understand the context of each node compared to others.

this is not about natural language, it's rather about the point and images.
i want to tell what is the order of the detected text-line images.
How should i go about that.

![demo](https://user-images.githubusercontent.com/49877135/84791600-83234400-affb-11ea-9a38-9d34285bcacd.gif)

**Comment by amirkhas** [comment]
Hi, please email if you want to discuss about this. Thanks.

**Comment by deepseek** [comment]
i prefer a simple explanation of how to solve it

**Comment by ghost** [comment]
@amirkhas  What is your email?
