### ISSUE TITLE
LiDAR and molecular use cases

### ISSUE THREAD

**Issue by fredmonroe** [amirkhas/GraphMemoryNet#5]
Hi Amir, saw your talk on youtube today. Was having a hard time finding your email - i'd like to speak w/ you briefly about applications to point cloud data (supervised)  and molecular data (unsupervised + supervised) for two specific problems i'm working on. If you'd be willing to chat with me briefly on zoom or something about this please contact me at fred@313v.com

Thank you, very nice presentation!

**Comment by amirkhas** [comment]
Hi, I'll send an email.
